### ISSUE TITLE
twn works not so good..

### ISSUE THREAD

**Issue by douzsh** [eldercrow/additions_mxnet#1]
Hi, Thanks very much for your sharing your codes.
I read your twn python ops and do some test on it.

I think there's a big problem is that when we update weight with twn-ops, although conv ops using the updated equalization weights, the backward did not update it. Loss only do effect on the original weights. 

This will make  the weights updated not effective.  

With this I want to assign the in_data[0] from out_data[0] when forward.  I failed because in_data[0] is read only.....

I'm not familiar with MXNet yet. Can you help me solve the problem?

**Comment by eldercrow** [comment]
Not sure if I understood your question correctly, but the followings are how I use the python op.
You need to first declare a convolution weight that will be ternarized, then pass it to the ternarization op, and feed it to the convolution operator. 

``` python
def conv_twn(data, num_filter, nch, name=None, kernel=(1,1), pad=(0,0), stride=(1,1), no_bias=False):
    ''' ternary weight convolution '''
    shape = (num_filter, nch, kernel[0], kernel[1])
    conv_weight = mx.sym.var(name=name+'_weight', 
            shape=shape, attr={'__wd_mult__': '0.0', '__lr_mult__': '0.0'}, dtype='float32')
    weight, alpha = mx.sym.Custom(conv_weight, op_type='ternarize_ch', th_ratio=1.0)
    weight = mx.sym.broadcast_mul(weight, alpha)
    conv = mx.sym.Convolution(data=data, weight=weight, name=name, num_filter=num_filter, 
            kernel=kernel, pad=pad, stride=stride, no_bias=no_bias)
    return conv


def fc_twn(data, num_hidden, nch, name=None, no_bias=False):
    ''' ternary weight fc '''
    fc_weight = mx.sym.var(name=name+'_weight', shape=(num_hidden, nch), 
            attr={'__wd_mult__': '0.0', '__lr_mult__': '0.0'}, dtype='float32')
    weight, alpha = mx.sym.Custom(fc_weight, op_type='ternarize_ch', th_ratio=1.0)
    weight = mx.sym.broadcast_mul(weight, alpha)
    fc = mx.sym.FullyConnected(data=data, weight=weight, name=name, num_hidden=num_hidden, no_bias=no_bias)
    return fc
```

**Comment by douzsh** [comment]
Thanks a lot!!
thatz what I want!
